Login
povio-academy/lj_backend_june_2024 pull request #28
Opened 2024-06-20 18:21 UTC by AljazKnific

2024-06-20 19:43 UTC, VitoDrofenik approved these changes

2024-06-21 11:27 UTC, njokc10 requested changes

2024-06-21 11:27 UTC, njokc10 commented on src/data-api/auth/dto/login.req.dto.ts
> +  @Expose()
I think it would be better if we do not expose password

2024-06-22 20:58 UTC, AljazKnific commented on src/data-api/auth/dto/login.req.dto.ts
> +  @Expose()
I agree, will fix the code :)

2024-06-22 20:58 UTC, closed without merging